location:
  tide_station_id: "9412110"  # NOAA station ID for Port San Luis
  lat: 35.32743152867097
  lon: -120.84221781139401

thresholds:
  min_tide_ft: 3.0
  min_tide_duration_minutes: 90
  max_wind_speed_mph: 7
  min_temperature_f: 50
  max_chance_of_rain_percent: 20

schedule:
  daily_run_time: "21:00"  # 9 PM local time

time_buffer:
  minutes_before_sunrise: 30
  minutes_after_sunset: 30

weather_api:
  service: "wu"
  wind_sources:
    - "wu"
    - "noaa_gfs"

llm:
  provider: "openai"  # or "anthropic"
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 300
