name: Deploy Frontend

on:
  push:
    branches: [main, master, GPT5-attempt]
    paths:
      - "src/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
      - name: Sync src to gh-pages root
        run: |
          rsync -av --delete --exclude 'data/' src/ gh-pages/
      - name: Commit and push
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy frontend [skip ci]" || echo "No changes"
          git push origin gh-pages
